#! /bin/bash
echo Downloading PiDisplay, please wait...
sudo wget https://github.com/bearcanrun/pi-display/releases/download/v0.1.0/PiDisplay.0.1.0.tar.xz
echo Download OK.
echo Unzipping...please be patient...
sudo tar -xavf PiDisplay.0.1.0.tar.xz
echo Installing...
sudo cp ./PiDisplay /usr/bin/
sudo chmod +x /usr/bin/PiDisplay
echo PiDisplay installed at /usr/bin/PiDisplay
sudo touch runPiDisplay.sh
sudo chmod +x runPiDisplay.sh
sudo cat >> runPiDisplay.sh <<EOL
echo Starting up PiDisplay...
sudo /usr/bin/PiDisplay
EOL
sudo touch uninstallPiDisplay.sh
sudo chmod +x uninstallPiDisplay.sh
sudo cat >> uninstallPiDisplay.sh <<EOL
echo Uninstalling PiDisplay...
cd /home/pi
sudo systemctl stop PiDisplay
sudo rm /usr/lib/systemd/system/PiDisplay.service
sudo rm /usr/bin/PiDisplay
sudo rm -rf PiDisplay && echo PiDisplay uninstalled
EOL
echo Installing service...
sudo touch /usr/lib/systemd/system/PiDisplay.service
sudo cat >> /usr/lib/systemd/system/PiDisplay.service <<EOL
[Unit]
Description=PiDisplay
After=network.target

[Service]
WorkingDirectory=/home/pi
ExecStart=/home/pi/PiDisplay/runPiDisplay.sh
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
EOL
sudo systemctl enable PiDisplay
sudo systemctl daemon-reload
echo Starting PiDisplay...
sudo systemctl start PiDisplay
sudo systemctl status PiDisplay
echo Cleaning up...
sudo rm PiDisplay
sudo rm PiDisplay.0.1.0.tar.xz
echo Installation complete!
